name: release-to-slack
description: Creates a Slack post containing the release notes and publishes it
author: Realm
inputs:
  atlasUrl:
    required: false
    description: The Atlas url. Default is https://cloud-dev.mongodb.com.
  realmUrl:
    required: false
    description: The MongoDB Realm url. Default is https://realm-dev.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
  appsPath:
    requireD: true
    description: The path to the apps to import into MongoDB Realm.

runs:
  using: node12
  main: dist/index.js
