name: release-to-slack
description: Creates a Slack post containing the release notes and publishes it
author: Realm
inputs:
  atlasUrl:
    required: true
    description: The Atlas url - e.g. https://cloud-dev.mongodb.com.
  realmUrl:
    required: true
    description: The MongoDB Realm url - e.g. https://realm-dev.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
  appsPath:
    required: true
    description: The path to the apps to import into MongoDB Realm.
  cluster-differentiator:
    required: true
    description: Provide a differentiator for the build - e.g. "{{ matrix.os }}-{{ matrix.node-version }}"  or "integration tests"
  cleanup:
    required: false
    description: A flag to indicate this is a cleanup job - it will tear down any apps and clusters created with the same parameters.
runs:
  using: node12
  main: dist/index.js
