name: release-to-slack
description: Creates a Slack post containing the release notes and publishes it
author: Realm
inputs:
  atlasUrl:
    required: true
    description: The Atlas url - e.g. https://cloud-dev.mongodb.com.
  realmUrl:
    required: true
    description: The MongoDB Realm url - e.g. https://realm-dev.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
  appsPath:
    required: true
    description: The path to the apps to import into MongoDB Realm.
runs:
  using: node12
  main: dist/main/index.js
  post: dist/cleanup/index.js
